title: 「Pythonによる計算物理」サポートページ
author:
  name: Junya Otsuki
  email: j.otsuki@okayama-u.ac.jp

description: >
  「Pythonによる計算物理」大槻純也 著（森北出版）のサポートページです。

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
