title: 「Pythonによる計算物理」 大槻純也 著
# logo: /assets/img/logo.png
logo: 9784627170810.jpg

description: >
  書籍「Pythonによる計算物理」大槻純也 著（森北出版）のサポートページです。本に掲載されているソースコードや更新情報を提供します。出版社のページは[こちら](https://www.morikita.co.jp/books/mid/017081)。
  <a href="https://www.morikita.co.jp/books/mid/017081">こちら</a>

show_downloads: false
google_analytics:

# theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
